### ISSUE TITLE
feat: badges user

### ISSUE THREAD

**Issue by gabrielamarqs** [shelfiie/Shelfie-back-end#111]
** desenvolver as rotas das badges do usuário: **
- implementar duas classes para as badges, uma com os dados da badge outra para as badges do usuário (utilizando enum)
- implementar rotas para badges:
     - get badges, update badges
- implementar rotas para user badges: 
     - ver como relacionar os enums com os badges 
     - get user badges, update badges
- setar para inicializar com as imagens das rotas

**Comment by gabrielamarqs** [comment]
@mayspiek 
depois dá uma olhada na issue #108, eu coloquei uns prints lá errado, devia ter posto aqui

já fiz estas rotas no back, depois vou subir pra vm

- essa é a update badges, só dá para modificar a url da imagem e a description, se você deixar em branco, ele não seta nada
![image](https://github.com/user-attachments/assets/e805c511-bf86-4c5b-b8a4-253169626e91)

- e para pegar todas as badges tem essa rota
![image](https://github.com/user-attachments/assets/23feb313-9937-4b98-9671-14f26590e178)

Atualmente, só temos essas duas rotas para a badge e não vejo necessidade de adicionar mais, já que novas badges precisam ser criadas no back-end primeiro e estou configurando as imagens na seeder. No entanto, se você achar que é necessário, me avise com suas sugestões.

**Comment by gabrielamarqs** [comment]
@mayspiek 

Atualizei as enuns 
![image](https://github.com/user-attachments/assets/8873cb7a-8812-4b74-98b5-c2e501e4be48)
![image](https://github.com/user-attachments/assets/7669b577-cd03-4a45-8a9e-9118f2615bcc)
![image](https://github.com/user-attachments/assets/4918ed5a-79e6-4115-b63b-e11aea15f9d6)

a rota que retorna todas infos da badge 
![image](https://github.com/user-attachments/assets/d8162f08-3b75-41de-a3b0-8d384536ed3a)

**Comment by mayspiek** [comment]
para registro, tradução dos enums:

LIVROS
- Leitor
- Rato de Biblioteca
- Bibliófilo
- Bibliomaníaco

PAGINOMETRO:
- 100 Páginas
- 1000 páginas
- Muitas Páginas

REVIEW:
- Novato
- Crítico
- Expert
- Connoisseur
