### ISSUE TITLE
fazer rota que retorna todos os dados do books que esta no mybooks

### ISSUE THREAD

**Issue by mayspiek** [shelfiie/Shelfie-back-end#33]

**Comment by gabrielamarqs** [comment]
seja mais específica, era aquilo que a gente tava falando de retornar review reading progression etc ?

**Comment by gabrielamarqs** [comment]
review, nota, dados do livro

**Comment by mayspiek** [comment]
Para registro:
Conforme alinhado no Whats as outras informações necessárias no retorno:

- Média das Ratings do Livro (Prioridade baixa)
- Quantas paginas o usuário já leu (montante das paginas contadas nos progressos)

**Comment by mayspiek** [comment]
Para registro, conforme comentado no whats:

- O retorno dessas informações podem ser feitos na rota de Get All My Books `/api/mybooks`
Atualmente você me retorna os seguintes dados:


![Image](https://github.com/user-attachments/assets/5a9a1bc0-a7f0-4149-998b-18317ec0fb75)

Isso já supre o seguinte requerimento

- [ ] Status do livro no usuário autenticado (se ele está na lista de lendo, lido, abandonado...etc)

As Reviews e Progression por livro você me retorna nas rotas
`/api/review/book/{bookId}` e `/api/reading/{bookId}` respectivamente. Atendendo a:
- [ ] Reviews POR LIVRO 

Então falta as seguintes infos:

- [ ] Média das ratings do livro a partir de todas as reviews existentes na API  (Prioridade BAIXA)
- [ ] Quantas paginas o usuário já leu daquele livro - montante das paginas contadas nos progressos (Prioridade ALTA)
- [ ] Dados do livro como ISBN, id da Api do Google e do Shelfie, link da imagem.

Os problemas que tenho em relação ao não retorno dos dados do livro:


![Image](https://github.com/user-attachments/assets/68f58189-538d-4fcf-874a-6da844ea44bd)

Ao mostrar os livros na Biblioteca do usuário, não possuo título e nem imagem dos livros.
Além de que eu gostaria de colocar um hiperlink em cada miniatura para redirecionar os usuários para a página `BookDetails` mas essa página recebe por parâmetro o ID do Google e faz a pesquisa pra retornar os dados nos detalhes. Então eu precisaria do retorno da ID do google de cada livro no fetch, assim consigo mandar o ID quando é chamado o componente e o usuário pra essa página sem intercorrências e também, provavelmente não será preciso criar outra rota para o retorno dessas infos, apenas a adição desses atributos no retorno da busca dos livros.

**Comment by gabrielamarqs** [comment]
@mayspiek 

só não estou mandando o status junto
> * Dados do livro como ISBN, id da API Shelfie e API google, link da imagem, status

Essa rota já existe
> * Status do livro no usuário autenticado (se ele está na lista de lendo, lido, abandonado...etc)
> 
> >

Essa regra de negócio já está implementada
> O item acima, assim como alinhado via Whats se refere a requisição de troca desse livro na lista do usuário e aplicar as RN do sistema, como por exemplo, que não pode fazer uma review se o livro não estiver no status lido ou abandonado e também não sera possível fazer a progressão caso o livro está com esses status)

As rota de pegar as reviews por livro já existe, sobre a nota, acho que tenho que mandar numa rota separada, a não ser que eu te mande todas as notas e vocÊ faz a media
> * Reviews POR LIVRO
> * Notas POR LIVRO (1 a 5)

**Comment by gabrielamarqs** [comment]
@mayspiek arrumei para se retornar null adicionar aquela url padrão, se não funcionar me passa um googleId que não funciona para eu testar

**Comment by gabrielamarqs** [comment]
@mayspiek adicionei o atributo do paginômetro, mas ele só retorna nas rotas users/me e na users/:userId, ainda não implementei uma lógica ainda porque temos que decidir umas regras de negócio

**Comment by mayspiek** [comment]
@gabrielamarqs na rota `/api/books/google/{googleId}` tem como vc receber ou o id do google ou o id da api?

**Comment by mayspiek** [comment]
@gabrielamarqs pra registro: retornar o bookId nas progression e adicionar a descrição na rota de get do mybooka
