### ISSUE TITLE
me retornar um atributo que fale se aquele book esta no mybooks

### ISSUE THREAD

**Issue by mayspiek** [shelfiie/Shelfie-back-end#34]

**Comment by gabrielamarqs** [comment]
Rota feita!
url: /api/mybooks/is-enabled/{googleId}
Se você passar um id que não existe no banco de dados ou que não está associado ao usuário, ele te retorna um 404. Então acho que isso vai te ajudar a definir quando é um create ou um update. 
![Screenshot from 2024-07-12 22-15-52](https://github.com/user-attachments/assets/cb07d6ab-b040-441a-9370-cb603b38ab95)

**Comment by gabrielamarqs** [comment]
@mayspiek porque você precisa desse id? Tem que ser o id do livro mesmo, ou do mybooks?
Arrumei a rota do update, então se o mybooks estiver disabled, ao mudar o status do livro, ela fica enabled
