### ISSUE TITLE
Mudar id recebido pelo body na reading progression

### ISSUE THREAD

**Issue by mayspiek** [shelfiie/Shelfie-back-end#37]
Ao fazer a progressão da leitura, a rota '/api/reading' recebe no body o id do MyBooks e não do livro em si.
Favor alterar.
![Image](https://github.com/user-attachments/assets/db50d3cb-2637-49f6-bfe5-12ccbb8bd39f)
![Image](https://github.com/user-attachments/assets/dc376ab3-a8f0-4ac7-bba8-0756842f37af)

**Comment by gabrielamarqs** [comment]
Ja subi as alterações, favor conferir

**Comment by mayspiek** [comment]
Conferido e aprovado.
