### ISSUE TITLE
fix: googleId como parâmetro para receber myBooks

### ISSUE THREAD

**Issue by gabrielamarqs** [shelfiie/Shelfie-back-end#58]

**Comment by gabrielamarqs** [comment]
@mayspiek essa essa rota?
![image](https://github.com/user-attachments/assets/876e854c-bfb4-4d0e-9588-d7d9dfe547d0)

**Comment by mayspiek** [comment]
sim tenkyu veri muchi

**Comment by mayspiek** [comment]
ta @gabrielamarqs mas pq q retorna uma lista? não era pra retornar 1 obj só?
