### ISSUE TITLE
retorno 500 da rota /api/pages/mine

### ISSUE THREAD

**Issue by mayspiek** [shelfiie/Shelfie-back-end#73]
Após as alterações de desabilitar a progressão quando o livro esta desabilitado, essa rota começou me retornar erro 500

![Image](https://github.com/user-attachments/assets/05a0cfba-b3c6-4e37-95d2-966c5697e2da)

em testes, fiz uma nova conta e enquanto eu não fiz uma progressão de um livro, continuou me retornando 500. depois de fazer uma progressão, o paginômetro funcionou normalmente

![Image](https://github.com/user-attachments/assets/690f981e-f4d3-457d-8a56-267252e3dea0)

nas outras contas utilizadas pra teste (admin e danielprofessor) tinha alguns livros que estavam desabilitados e as duas me davam o mesmo erro 50

**Comment by gabrielamarqs** [comment]
As duas rotas estão funcionando normalmente para mim, criei um usuário novo, loguei e não fiz mais nada, funcionou normal
![image](https://github.com/user-attachments/assets/dc01a97e-7867-4ed2-99c5-52fa626d5112)
![image](https://github.com/user-attachments/assets/6ae26895-82e1-43f0-8c56-86d28115d520)

**Comment by gabrielamarqs** [comment]
@mayspiek 
acredito que este problema está resolvido
