### ISSUE TITLE
erro no retorno das paginas de cada progressao

### ISSUE THREAD

**Issue by mayspiek** [shelfiie/Shelfie-back-end#74]
Ao fazer um fetch de todas as progressoes, as paginas me retornam corretamente

![Image](https://github.com/user-attachments/assets/b039de77-3be9-4a44-bd3e-8f424b4b48ba)

mas ao fazer de cada id, o retorno é o mesmo = a última página

fetch com id da primeira progressão (15 paginas)

![Image](https://github.com/user-attachments/assets/e0a749fb-9cab-47c2-a342-2b3ffa44624b)

**Comment by gabrielamarqs** [comment]
@mayspiek rota fixed
